CREATE TABLE [dbo].[Agendamentos](
	[Cd_Agendamento] [int] NOT NULL,
	[Dat_Agendamento] [datetime] NOT NULL,
	[Cd_Status] [int] NULL,
	[Cd_Cliente] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Cd_Agendamento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Agendamentos]  WITH CHECK ADD FOREIGN KEY([Cd_Cliente])
REFERENCES [dbo].[pessoas] ([cod_pessoa])
GO

CREATE INDEX IDX_AGENDAMENTOSDAT ON AGENDAMENTOS(DAT_AGENDAMENTO)
GO
CREATE INDEX IDX_AGENDAMENTOSCLI ON AGENDAMENTOS([Cd_Cliente])

