INSERT INTO SIS_MODULOS
(DS_MOD_MODULO)
VALUES ('AGENDAMENTOS')
GO

INSERT INTO SIS_URLS
(cd_id_modulos, ds_url)
VALUES
(23, 'http://192.168.100.5/agendamentos')
GO

UPDATE SIS_MODULOS 
SET DS_MOD_CHAVE = '1000:yNgsBPDgZSctFzLyjhaTluIBnomVTs47:xXFfTR3bxPKQlDoWWIYH2dWRbIjsxePW'
WHERE CD_ID = 23